name: Merge Trunk CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Ewallet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ewallet/requirements.txt
      
      - name: Run tests
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python ewallet/manage.py makemigrations
          python ewallet/manage.py migrate
          python ewallet/manage.py test accounts
          python ewallet/manage.py test finance

      - name: Build Docker image ewallet
        run: |
          docker build -t ewallet:${{ github.sha }} -f ewallet/Dockerfile ewallet/
      
      - name: Push Docker image
        env:
            DJANGO_SECRET_KEY: ${{ secrets.DOCKER_PASSWORD }}
            API_KEY: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ewallet:${{ github.sha }}